VendorID=
ProductID=

Serial_String_Enable=y
Product_String_Enable=y
Manufacturer_String_Enable=y
Serial_String=abcdef
Product_String=USB serial
Manufacturer_String=wch.cn

MaxPower(mA)=
PowerMode=
Remote_Wakeup_Enable=

PIN_USE_EEPROM_Enable=n
CDC_CTSRTS_FlowControl_Enable=
TurnOff_SuspendMode_Enable=n

# CH344/CH348/CH9114
DTR_MUX_TNOW_SoftSet_Enable=n
UARTx_TNOW_DTR_SETBITS=
# CH9105
CH9105_GPIO_Enable=
CH9105_GPIO_Enable_BITS=
# CH9101RY
CH9101RY_MODEM_Enable=
CH9101RY_TXS_MUX_DSR_Enable=
CH9101RY_RXS_MUX_RI_Enable=
CH9101RY_TNOW_MUX_DCD_Enable=
CH9101RY_SLEEP_MUX_DTR_Enable=
# CH346
CH346_Config_Enable=n
CH346_Config_Freq=
CH346_Config_Mode=
CH346_Config_PLen=
CH346_Config_M0_IO0=
CH346_Config_M0_IO1=
CH346_Config_M1_IO0=
CH346_Config_M1_IO1=
CH346_Config_M2_IO0=
CH346_Config_M2_IO1=
CH346_Config_M2_IO2=
CH346_Config_M2_IO3=
